homeassistant:
  # Name of the location where Home Assistant is running
  name: "Site Name"
  # Location required to calculate the time the sun rises and sets
  latitude: "XX.xx"
  longitude: "XX.xx"
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 75
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  #Whitelist
  whitelist_external_dirs: /tmp
  #Customization.yaml Include
  customize: !include customize.yaml

  # Enables configuration UI
config:
#  sensor: !include sensor.yaml
  sensor:
  - platform: yr
  - platform: template
  - platform: mqtt
    name: "Node RED"
    state_topic: "checkIn/nodeRED"
    expire_after: 300
  - platform: time_date
    display_options:
      - 'time_date'
#Iframe_Panels for easier access
panel_iframe:
    configurator:
        title: Configurator
        icon: mdi:wrench
        url: http://(insert homeassistant ip):3218
    tasmoadmin:
        title: TasmoAdmin
        icon: mdi:atom
        url: http://(insert homeassistant ip):9541
    nodered:
        title: NodeRed
        icon: mdi:biohazard
        url: http://(insert homeassistant ip):1880

#Xiaomi Aqara Alarm
xiaomi_aqara:
  discovery_retry: 10
  gateways:
   - mac: !Xiaomi Gateway Mac Address
     host: (insert Xiaomi Gateway ip)
     key: !secret key


# Enables the frontend
http:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

#DeCONS RaspBee
deconz:
  host: !Include RaspBee IP
# Change the port below to the one chosen in the addon
  port: 8080
  
# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

#MQTT
mqtt:
  broker: (insert MQTT ip)
  port: 1883
  username: username
  password: password

#Media Player for Alarm Sound
media_player:
  - platform: mpd
    name: mediaplayer
    host: (insert homeassistant ip)

frontend:
  javascript_version: latest

# Track the sun
sun:

#Unifi Camera System
camera:
  - platform: uvc
    nvr: !NVR IP Address
    key: !secret API
    password: !Camera Password

#Twilio
twilio:
  account_sid: !secret
  auth_token: !secret

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /config/tts/
    time_meory: 300
    language: 'en'

#WatchDog CheckIN
input_boolean:
  node_red:
    name: Node Red Watchdog
    initial: on


notify: !include notify.yaml
alarm_control_panel: !include alarm.yaml
panel_custom: !include panel_custom.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
